name: python-ETL-02
on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 13 * * *'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: install
      run: |
        echo '''${{ secrets.FIREBASE_JSON }}''' > serviceAccount.json
        echo -n '''${{ secrets.ETL_02 }}''' > ETL_02.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python test
      run: |
        python3 321.py
